### ISSUE TITLE
New files use encoding of app.json

### ISSUE THREAD

**Issue by LeonStaufer** [JYC333/Anki-Sync-to-Obsidian#4]
New files are created using the encoding of `app.json` which can cause problems, see below:

```
Caught exception:
Traceback (most recent call last):
  File "/Users/leon/Library/Application Support/Anki2/addons21/327710559/main.py", line 132, in sync
    sync_to_obsidian(browser)
  File "/Users/leon/Library/Application Support/Anki2/addons21/327710559/main.py", line 99, in sync_to_obsidian
    f.write(f"\n{field}\n")
UnicodeEncodeError: 'ascii' codec can't encode character '\xea' in position 32: ordinal not in range(128)
```

Perhaps instead of this encoding, the relevant encoding for the current note type could be used.
https://github.com/JYC333/Anki-Sync-to-Obsidian/blob/99e896499f40aaed675d520e0424171c074d2319/main.py#L73

**Comment by JYC333** [comment]
Sorry for the late update, now it will use the default encoding from system
